import {
  Product,
  Order,
  Category,
  Notification,
  OrderItem,
  Address,
  DashboardStats,
} from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'High-quality noise-cancelling wireless headphones with 30-hour battery life.',
    sku: 'WH-001',
    status: 'active',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-20T14:30:00Z',
    productProperties: [
      { id: '1', productId: '1', name: 'Color', value: 'Black', type: 'color' },
      { id: '2', productId: '1', name: 'Bluetooth Version', value: '5.2', type: 'text' },
      { id: '3', productId: '1', name: 'Battery Life', value: '30', type: 'number' },
    ],
    productPricing: {
      id: '1',
      productId: '1',
      basePrice: 299.99,
      compareAtPrice: 349.99,
      costPrice: 150.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '1',
        productId: '1',
        url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
        alt: 'Wireless Headphones',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '1',
      name: 'Electronics',
      slug: 'electronics',
      productCount: 25,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '2',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable 100% organic cotton t-shirt available in multiple colors.',
    sku: 'TS-002',
    status: 'active',
    createdAt: '2024-01-18T10:00:00Z',
    updatedAt: '2024-01-22T09:15:00Z',
    productProperties: [
      { id: '4', productId: '2', name: 'Size', value: 'Large', type: 'size' },
      { id: '5', productId: '2', name: 'Color', value: 'Navy Blue', type: 'color' },
      { id: '6', productId: '2', name: 'Material', value: 'Organic Cotton', type: 'text' },
    ],
    productPricing: {
      id: '2',
      productId: '2',
      basePrice: 29.99,
      compareAtPrice: 39.99,
      costPrice: 12.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '2',
        productId: '2',
        url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
        alt: 'Cotton T-Shirt',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '2',
      name: 'Fashion',
      slug: 'fashion',
      productCount: 45,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '3',
    name: 'Stainless Steel Water Bottle',
    description: 'Insulated stainless steel water bottle keeps drinks cold for 24 hours.',
    sku: 'WB-003',
    status: 'out_of_stock',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-25T16:45:00Z',
    productProperties: [
      { id: '7', productId: '3', name: 'Capacity', value: '32oz', type: 'size' },
      { id: '8', productId: '3', name: 'Material', value: 'Stainless Steel', type: 'text' },
    ],
    productPricing: {
      id: '3',
      productId: '3',
      basePrice: 24.99,
      compareAtPrice: undefined,
      costPrice: 10.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '3',
        productId: '3',
        url: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=500',
        alt: 'Water Bottle',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '3',
      name: 'Sports & Outdoors',
      slug: 'sports-outdoors',
      productCount: 18,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '4',
    name: 'Smart Watch Pro',
    description: 'Feature-rich smartwatch with health tracking and GPS.',
    sku: 'SW-004',
    status: 'active',
    createdAt: '2024-01-22T10:00:00Z',
    updatedAt: '2024-01-23T14:00:00Z',
    productProperties: [
      { id: '9', productId: '4', name: 'Color', value: 'Black', type: 'color' },
      { id: '10', productId: '4', name: 'Battery Life', value: '48 hours', type: 'text' },
    ],
    productPricing: {
      id: '4',
      productId: '4',
      basePrice: 199.99,
      compareAtPrice: 249.99,
      costPrice: 120.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '4',
        productId: '4',
        url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
        alt: 'Smart Watch',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '1',
      name: 'Electronics',
      slug: 'electronics',
      productCount: 25,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '5',
    name: 'Running Shoes',
    description: 'Comfortable running shoes with cushion technology.',
    sku: 'RS-005',
    status: 'active',
    createdAt: '2024-01-24T10:00:00Z',
    updatedAt: '2024-01-25T09:00:00Z',
    productProperties: [
      { id: '11', productId: '5', name: 'Size', value: '10', type: 'size' },
      { id: '12', productId: '5', name: 'Color', value: 'White', type: 'color' },
    ],
    productPricing: {
      id: '5',
      productId: '5',
      basePrice: 89.99,
      compareAtPrice: 119.99,
      costPrice: 45.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '5',
        productId: '5',
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
        alt: 'Running Shoes',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '3',
      name: 'Sports & Outdoors',
      slug: 'sports-outdoors',
      productCount: 18,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '6',
    name: 'Designer Handbag',
    description: 'Luxury leather handbag with modern design.',
    sku: 'HB-006',
    status: 'active',
    createdAt: '2024-01-25T10:00:00Z',
    updatedAt: '2024-01-26T11:00:00Z',
    productProperties: [
      { id: '13', productId: '6', name: 'Color', value: 'Brown', type: 'color' },
      { id: '14', productId: '6', name: 'Material', value: 'Genuine Leather', type: 'text' },
    ],
    productPricing: {
      id: '6',
      productId: '6',
      basePrice: 299.99,
      compareAtPrice: 399.99,
      costPrice: 150.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '6',
        productId: '6',
        url: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=500',
        alt: 'Handbag',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '2',
      name: 'Fashion',
      slug: 'fashion',
      productCount: 45,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '7',
    name: 'Bluetooth Speaker',
    description: 'Portable wireless speaker with 360-degree sound.',
    sku: 'BS-007',
    status: 'active',
    createdAt: '2024-01-26T10:00:00Z',
    updatedAt: '2024-01-27T10:00:00Z',
    productProperties: [
      { id: '15', productId: '7', name: 'Color', value: 'Blue', type: 'color' },
      { id: '16', productId: '7', name: 'Battery Life', value: '20 hours', type: 'text' },
    ],
    productPricing: {
      id: '7',
      productId: '7',
      basePrice: 79.99,
      compareAtPrice: 99.99,
      costPrice: 40.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '7',
        productId: '7',
        url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500',
        alt: 'Bluetooth Speaker',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '1',
      name: 'Electronics',
      slug: 'electronics',
      productCount: 25,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '8',
    name: 'Yoga Mat',
    description: 'Non-slip yoga mat with carrying strap.',
    sku: 'YM-008',
    status: 'active',
    createdAt: '2024-01-27T10:00:00Z',
    updatedAt: '2024-01-28T09:00:00Z',
    productProperties: [
      { id: '17', productId: '8', name: 'Color', value: 'Purple', type: 'color' },
      { id: '18', productId: '8', name: 'Thickness', value: '6mm', type: 'text' },
    ],
    productPricing: {
      id: '8',
      productId: '8',
      basePrice: 34.99,
      compareAtPrice: 49.99,
      costPrice: 15.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '8',
        productId: '8',
        url: 'https://images.unsplash.com/photo-1601925260368-ae2f83d34b5e?w=500',
        alt: 'Yoga Mat',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '3',
      name: 'Sports & Outdoors',
      slug: 'sports-outdoors',
      productCount: 18,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '9',
    name: 'Laptop Backpack',
    description: 'Sleek laptop backpack with multiple compartments.',
    sku: 'LB-009',
    status: 'active',
    createdAt: '2024-01-28T10:00:00Z',
    updatedAt: '2024-01-29T10:00:00Z',
    productProperties: [
      { id: '19', productId: '9', name: 'Color', value: 'Gray', type: 'color' },
      { id: '20', productId: '9', name: 'Capacity', value: '17 inches', type: 'text' },
    ],
    productPricing: {
      id: '9',
      productId: '9',
      basePrice: 59.99,
      compareAtPrice: 79.99,
      costPrice: 25.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '9',
        productId: '9',
        url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
        alt: 'Laptop Backpack',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '2',
      name: 'Fashion',
      slug: 'fashion',
      productCount: 45,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '10',
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with long battery life.',
    sku: 'WM-010',
    status: 'active',
    createdAt: '2024-01-29T10:00:00Z',
    updatedAt: '2024-01-30T10:00:00Z',
    productProperties: [
      { id: '21', productId: '10', name: 'Color', value: 'Black', type: 'color' },
      { id: '22', productId: '10', name: 'Connection', value: 'Bluetooth/USB', type: 'text' },
    ],
    productPricing: {
      id: '10',
      productId: '10',
      basePrice: 29.99,
      compareAtPrice: 39.99,
      costPrice: 12.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '10',
        productId: '10',
        url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500',
        alt: 'Wireless Mouse',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '1',
      name: 'Electronics',
      slug: 'electronics',
      productCount: 25,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '11',
    name: 'Denim Jeans',
    description: 'Classic fit denim jeans with stretch comfort.',
    sku: 'DJ-011',
    status: 'active',
    createdAt: '2024-01-30T10:00:00Z',
    updatedAt: '2024-01-31T09:00:00Z',
    productProperties: [
      { id: '23', productId: '11', name: 'Size', value: '32x34', type: 'size' },
      { id: '24', productId: '11', name: 'Color', value: 'Blue', type: 'color' },
    ],
    productPricing: {
      id: '11',
      productId: '11',
      basePrice: 49.99,
      compareAtPrice: 69.99,
      costPrice: 20.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '11',
        productId: '11',
        url: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
        alt: 'Denim Jeans',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '2',
      name: 'Fashion',
      slug: 'fashion',
      productCount: 45,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
  {
    id: '12',
    name: 'Fitness Tracker',
    description: 'Advanced fitness tracker with heart rate monitor.',
    sku: 'FT-012',
    status: 'active',
    createdAt: '2024-01-31T10:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
    productProperties: [
      { id: '25', productId: '12', name: 'Color', value: 'Black', type: 'color' },
      { id: '26', productId: '12', name: 'Water Resistance', value: '5ATM', type: 'text' },
    ],
    productPricing: {
      id: '12',
      productId: '12',
      basePrice: 89.99,
      compareAtPrice: 119.99,
      costPrice: 45.00,
      currency: 'USD',
      taxIncluded: false,
    },
    productImages: [
      {
        id: '12',
        productId: '12',
        url: 'https://images.unsplash.com/photo-1579586337278-3befd40f17ca?w=500',
        alt: 'Fitness Tracker',
        isPrimary: true,
        order: 1,
      },
    ],
    category: {
      id: '1',
      name: 'Electronics',
      slug: 'electronics',
      productCount: 25,
      createdAt: '2024-01-10T10:00:00Z',
      updatedAt: '2024-01-10T10:00:00Z',
    },
    orderItems: [],
  },
];

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Electronic devices and accessories',
    productCount: 25,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
    children: [
      {
        id: '11',
        name: 'Audio',
        slug: 'electronics-audio',
        productCount: 12,
        parentId: '1',
        createdAt: '2024-01-10T10:00:00Z',
        updatedAt: '2024-01-10T10:00:00Z',
      },
      {
        id: '12',
        name: 'Mobile Accessories',
        slug: 'electronics-mobile-accessories',
        productCount: 13,
        parentId: '1',
        createdAt: '2024-01-10T10:00:00Z',
        updatedAt: '2024-01-10T10:00:00Z',
      },
    ],
  },
  {
    id: '2',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Clothing and fashion accessories',
    productCount: 45,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
    children: [
      {
        id: '21',
        name: 'Men',
        slug: 'fashion-men',
        productCount: 20,
        parentId: '2',
        createdAt: '2024-01-10T10:00:00Z',
        updatedAt: '2024-01-10T10:00:00Z',
      },
      {
        id: '22',
        name: 'Women',
        slug: 'fashion-women',
        productCount: 25,
        parentId: '2',
        createdAt: '2024-01-10T10:00:00Z',
        updatedAt: '2024-01-10T10:00:00Z',
      },
    ],
  },
  {
    id: '3',
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description: 'Sports equipment and outdoor gear',
    productCount: 18,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

const mockAddressesData: Address[] = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    company: 'Acme Inc.',
    addressLine1: '123 Main Street',
    addressLine2: 'Suite 100',
    city: 'New York',
    state: 'NY',
    postalCode: '10001',
    country: 'United States',
    phone: '+1-555-0123',
    isDefault: true,
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    addressLine1: '456 Oak Avenue',
    city: 'Los Angeles',
    state: 'CA',
    postalCode: '90001',
    country: 'United States',
    phone: '+1-555-0456',
    isDefault: false,
  },
];

export const mockAddresses: Address[] = mockAddressesData;

const mockShippingAddress: Address = mockAddressesData[0];
const mockBillingAddress: Address = mockAddressesData[1];

const mockOrdersData: Order[] = [
  {
    id: '1',
    orderNumber: 'ORD-2024-001',
    customerName: 'Alice Johnson',
    customerEmail: 'alice@example.com',
    status: 'processing',
    totalAmount: 329.98,
    currency: 'USD',
    createdAt: '2024-01-25T10:30:00Z',
    updatedAt: '2024-01-25T11:15:00Z',
    shippingAddress: mockShippingAddress,
    billingAddress: mockBillingAddress,
    orderItems: [
      {
        id: '1',
        orderId: '1',
        productId: '1',
        productName: 'Premium Wireless Headphones',
        quantity: 1,
        unitPrice: 299.99,
        totalPrice: 299.99,
      },
      {
        id: '2',
        orderId: '1',
        productId: '2',
        productName: 'Organic Cotton T-Shirt',
        quantity: 1,
        unitPrice: 29.99,
        totalPrice: 29.99,
      },
    ],
  },
  {
    id: '2',
    orderNumber: 'ORD-2024-002',
    customerName: 'Bob Williams',
    customerEmail: 'bob@example.com',
    status: 'shipped',
    totalAmount: 29.99,
    currency: 'USD',
    createdAt: '2024-01-24T14:20:00Z',
    updatedAt: '2024-01-25T09:00:00Z',
    shippingAddress: mockShippingAddress,
    billingAddress: mockBillingAddress,
    orderItems: [
      {
        id: '3',
        orderId: '2',
        productId: '2',
        productName: 'Organic Cotton T-Shirt',
        quantity: 1,
        unitPrice: 29.99,
        totalPrice: 29.99,
      },
    ],
  },
  {
    id: '3',
    orderNumber: 'ORD-2024-003',
    customerName: 'Charlie Brown',
    customerEmail: 'charlie@example.com',
    status: 'delivered',
    totalAmount: 24.99,
    currency: 'USD',
    createdAt: '2024-01-23T08:15:00Z',
    updatedAt: '2024-01-24T16:30:00Z',
    shippingAddress: mockShippingAddress,
    billingAddress: mockBillingAddress,
    orderItems: [
      {
        id: '4',
        orderId: '3',
        productId: '3',
        productName: 'Stainless Steel Water Bottle',
        quantity: 1,
        unitPrice: 24.99,
        totalPrice: 24.99,
      },
    ],
  },
  {
    id: '4',
    orderNumber: 'ORD-2024-004',
    customerName: 'Diana Prince',
    customerEmail: 'diana@example.com',
    status: 'pending',
    totalAmount: 299.99,
    currency: 'USD',
    createdAt: '2024-01-26T12:00:00Z',
    updatedAt: '2024-01-26T12:00:00Z',
    shippingAddress: mockShippingAddress,
    billingAddress: mockBillingAddress,
    orderItems: [
      {
        id: '5',
        orderId: '4',
        productId: '1',
        productName: 'Premium Wireless Headphones',
        quantity: 1,
        unitPrice: 299.99,
        totalPrice: 299.99,
      },
    ],
  },
];

export const mockOrders: Order[] = mockOrdersData;

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'New Order Received',
    message: 'You have received a new order (ORD-2024-004) from Diana Prince',
    type: 'success',
    isRead: false,
    createdAt: '2024-01-26T12:00:00Z',
    actionUrl: '/dashboard/orders/4',
  },
  {
    id: '2',
    title: 'Low Stock Alert',
    message: 'Premium Wireless Headphones is running low on stock (5 units remaining)',
    type: 'warning',
    isRead: false,
    createdAt: '2024-01-25T10:00:00Z',
    actionUrl: '/dashboard/products/1',
  },
  {
    id: '3',
    title: 'Order Shipped',
    message: 'Order ORD-2024-002 has been shipped successfully',
    type: 'info',
    isRead: true,
    createdAt: '2024-01-25T09:00:00Z',
    actionUrl: '/dashboard/orders/2',
  },
  {
    id: '4',
    title: 'Payment Received',
    message: 'Payment of $329.98 received for order ORD-2024-001',
    type: 'success',
    isRead: true,
    createdAt: '2024-01-24T15:00:00Z',
    actionUrl: '/dashboard/orders/1',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalProducts: 88,
  totalOrders: 156,
  totalRevenue: 45230.50,
  pendingOrders: 12,
  lowStockProducts: 5,
  totalCategories: 8,
  recentOrders: mockOrders.slice(0, 5),
  topProducts: [
    { productId: '1', productName: 'Premium Wireless Headphones', ordersCount: 45, revenue: 13499.55 },
    { productId: '2', productName: 'Organic Cotton T-Shirt', ordersCount: 89, revenue: 2669.11 },
    { productId: '3', productName: 'Stainless Steel Water Bottle', ordersCount: 23, revenue: 574.77 },
  ],
};

export const mockCompanies = [
  { id: '1', name: 'Acme Corporation' },
  { id: '2', name: 'Tech Industries' },
  { id: '3', name: 'Fashion Brands Ltd' },
  { id: '4', name: 'Global Supplies Inc' },
  { id: '5', name: 'Premium Goods Co' },
];

export interface ProductGroup {
  id: string;
  name: string;
  company: {
    id: string;
    name: string;
  };
  productCount: number;
  createdAt: string;
  updatedAt: string;
}

export const mockProductGroups: ProductGroup[] = [
  {
    id: '1',
    name: 'Electronics Group',
    company: { id: '1', name: 'Acme Corporation' },
    productCount: 25,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '2',
    name: 'Fashion Group',
    company: { id: '2', name: 'Tech Industries' },
    productCount: 45,
    createdAt: '2024-01-12T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '3',
    name: 'Sports Group',
    company: { id: '3', name: 'Fashion Brands Ltd' },
    productCount: 18,
    createdAt: '2024-01-14T10:00:00Z',
    updatedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: '4',
    name: 'Home & Living',
    company: { id: '1', name: 'Acme Corporation' },
    productCount: 32,
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-18T10:00:00Z',
  },
  {
    id: '5',
    name: 'Beauty & Personal Care',
    company: { id: '4', name: 'Global Supplies Inc' },
    productCount: 28,
    createdAt: '2024-01-18T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: '6',
    name: 'Automotive',
    company: { id: '5', name: 'Premium Goods Co' },
    productCount: 15,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-22T10:00:00Z',
  },
];

